---
version: '3.5'

x-args:
  &default-args
  NODE_ENV: development
  NPM_CONFIG_LOGLEVEL: info

services:
  jakkadi:
    container_name: node_jakkadi
    image: "jakkadi:dev"
    build:
      context: .
      args:
        *default-args
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      JAKKADI_POSTGRES_DATABASE: ${JAKKADI_POSTGRES_DATABASE:-jakkadi}
      JAKKADI_POSTGRES_USER: ${JAKKADI_POSTGRES_USER:-jakkadi}
      JAKKADI_POSTGRES_PASSWORD: ${JAKKADI_POSTGRES_PASSWORD:-jakkadi}
      JAKKADI_POSTGRES_HOST: ${JAKKADI_POSTGRES_HOST:-postgres}
    volumes:
      - ${PWD}:/usr/src/app
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always

  postgres:
    image: postgres
    container_name: pg_caravel
    environment:
      POSTGRES_DB: ${JAKKADI_POSTGRES_DATABASE:-jakkadi}
      POSTGRES_USER: ${JAKKADI_POSTGRES_USER:-jakkadi}
      POSTGRES_PASSWORD: ${JAKKADI_POSTGRES_PASSWORD:-jakkadi}
      POSTGRES_HOST: ${JAKKADI_POSTGRES_HOST:-postgres}
    ports:
      - "5432"

