---
version: '3.5'

x-args:
  &default-args
  http_proxy: "http://proxy.ubisoft.org:3128"
  https_proxy: "http://proxy.ubisoft.org:3128"
  no_proxy: "localhost, 127.0.0.1, .ubisoft.org, .ubisoft.onbe"
  NODE_ENV: ${NODE_ENV:-development}
  NPM_CONFIG_LOGLEVEL: info

services:
  caravel:
    container_name: node_caravel_int
    build:
      context: .
      args:
        *default-args
    environment:
      HZ_CARAVEL_POSTGRES_DATABASE: ${HZ_CARAVEL_POSTGRES_DATABASE:-caravel}
      HZ_CARAVEL_POSTGRES_USER: ${HZ_CARAVEL_POSTGRES_USER:-caravel}
      HZ_CARAVEL_POSTGRES_PASSWORD: ${HZ_CARAVEL_POSTGRES_PASSWORD:-caravel}
      HZ_CARAVEL_POSTGRES_HOST: ${HZ_CARAVEL_POSTGRES_HOST:-postgres}
      HZ_CARAVEL_REDIS_HOST: ${HZ_CARAVEL_REDIS_HOST:-redis}
      HZ_CARAVEL_SWIFT_USERNAME: ${HZ_CARAVEL_SWIFT_USERNAME}
      HZ_CARAVEL_SWIFT_PASSWORD: ${HZ_CARAVEL_SWIFT_PASSWORD}
      HZ_CARAVEL_SWIFT_CONTAINER: ci-caravel-integration-test
      HZ_CARAVEL_SWIFT_TENANTID:
        ${OS_PROJECT_ID:-d4d698c584eb4f3a8278c2db1124d28f}
      HZ_CARAVEL_SWIFT_REGION_NAME: ncsa-east-msr-onl
      HZ_CARAVEL_MATE_URL: ${HZ_CARAVEL_MATE_URL:-127.0.0.1}
      HZ_CARAVEL_HZFLAGS_VALIDATEREADPERMISSION:
        "${HZ_CARAVEL_HZFLAGS_VALIDATEREADPERMISSION:-false}"
    volumes:
      - ${PWD}:/usr/src/app
      - notused:/usr/src/app/node_modules
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"
    ports:
      - "8085"
    links:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: pg_caravel_int
    environment:
      POSTGRES_DB: ${HZ_CARAVEL_POSTGRES_DATABASE:-caravel}
      POSTGRES_USER: ${HZ_CARAVEL_POSTGRES_USER:-caravel}
      POSTGRES_PASSWORD: ${HZ_CARAVEL_POSTGRES_PASSWORD:-caravel}
      POSTGRES_HOST: ${HZ_CARAVEL_POSTGRES_HOST:-postgres}
    ports:
      - "5432"

  redis:
    image: redis
    container_name: redis_caravel_int
    ports:
      - "6379"
    command:
      - bash
      - -c
      - docker-entrypoint.sh --requirepass fake-password

volumes:
  notused:
